spring:
  redis:
    database: 0
    host: 192.168.101.215
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-wait: 2000
        max-idle: 500
        min-idle: 50
        max-active: 1000
    password: 199902



